services:
  api_prise_commandes:
    container_name: api_prise_commandes
    image: node:lts
    env_file: ./service/api_prise_commandes/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api_prise_commandes:/usr/src/app
    ports:
      - 3333:3000
    command: npm run watch
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  api_suivi_commandes:
    container_name: api_suivi_commandes
    image: node:lts
    env_file: ./service/api_suivi_commandes/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api_suivi_commandes:/usr/src/app
    ports:
      - 3334:3001
    command: npm run watch
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  api_gateway_back_office:
    container_name: api_gateway_back_office
    image: node:lts
    working_dir: /usr/src/app
    volumes:
      - ./service/api_gateway_back_office:/usr/src/app
    ports:
      - 3335:3002
    command: npm run watch
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  api_gateway_front_office:
    container_name: api_gateway_front_office
    image: node:lts
    working_dir: /usr/src/app
    volumes:
      - ./service/api_gateway_front_office:/usr/src/app
    ports:
      - 3336:3004
    command: npm run watch
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  iut_db:
    container_name: iut_db
    image: mariadb:latest
    env_file: ./service/.env
    volumes:
      - ./service/db:/var/lib/mysql
      - ./service/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./service/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - iut

  iut_adminer:
    container_name: iut_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - iut_db
    networks:
      - iut

networks:
  iut:
    driver: bridge
